sudo: false
language: node_js
node_js:
- '6'
env:
  global:
  - BROWSERSTACK_USERNAME: dtktestaccount1
  - BROWSERSTACK_ACCESS_KEY: mG2qbEFJCZY2qLsM7yfx
  - SAUCE_USERNAME: dojo2-ts-ci
  - SAUCE_ACCESS_KEY: e92610e3-834e-4bec-a3b5-6f7b9d874601
before_install:
- if [ ${TRAVIS_BRANCH-""} == "master" ] && [ -n ${encrypted_12c8071d2874_key-""}
  ]; then openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in deploy_key.enc -out deploy_key -d; fi
install:
- npm install grunt-cli
- npm install
script:
- grunt
- grunt intern:node --test-reporter
- grunt doc
notifications:
  slack:
    on_success: change
    secure: ZFnJrC/5SoJT6WPrChH92nZrZhOTPVznnrH5aegwGuCaoYxevjJkEpguuJmXt8cSh+pFrIECHjJvlDxt/LuuuhHVsytJWZQfhp+nemW99Qi004qHJni0Feqs37WnDKOhbifrGjXOtWv+cT7aPTXO/acLRymDtFOrm3YBCJAx/UyGrZPtOs3c1pFW6KFdX7GTyE/4wIxsi5eQkQdRw5Cyvy2VW3tm1ONoIH79qEjUHDtXdQNPXIS6rvtvOfDuNp4UfCGdZk6W+Gzox5fllKnDj8sjaD1/8LrvxOxYYtf5HMC5iFadWy8zAtBke5yWsxZ+Lkcw5tNAObR9ltbRiZ+BZlEJBE65zRHY6lSeNskU/gxoOPV19ZgAoLyr4zyOV1sJY3mQw3Bg6Fnyn5papRyDhaGTbfk3SfhDUQtNWugybRCR0/cGOBxG5hmgdxug/d9WnzlClmIJo7c/cq0OQn4LO9KvKcfASJ/y2Zk5QpJ7KVVNESqy0I7TpLQv6b1qhwGlnMRax4+S15RPcmvjCkbhb7a5UwUjAM7e18TklOviC+T6P2oMZR0XZ3cuHfhJ8gX0pK/mPYQNcPSOsFn1l/88zgiuyZ9KY+Gnu2y6Gs+slXOQCxc3PfvcxF/J7Ay1lNRipQL+FqHEjdDCQJPj3TjQgA1Bw0AG68/Sa405FoWnbF4=
